version: '3.1'

services:
  pgdb:
    image: postgres:14
    restart: always
    ports:
      - 6000:5432
    environment:
      POSTGRES_PASSWORD: localdb123
      POSTGRES_DB: sec
    volumes:
      - /home/michael/spysec/data:/var/lib/postgresql/data
  parser:
    restart: always
    volumes:
      - ./filings:/app/filings
    build:
      context: ./
