version: '3.1'

services:
  db:
    image: postgres:14
    restart: always
    ports:
      - 6000:5432
    environment:
      POSTGRES_PASSWORD: localdb123
    volumes:
      - /home/michael/Desktop/spysecdb/data:/var/lib/postgresql/data